### ISSUE TITLE
bug if empty file field

### ISSUE THREAD

**Issue by danfreak** [jrbasso/MeioUpload#9] opened 2009-08-25 09:34 UTC
When:
a) a record is edited
b) the record already has an image in database field
c) the "filename" field is left empty

the behavior tries to upload a file anyway and outputs the following errors:

Notice (8): Undefined index:  filename [APP/plugins/meio_upload/models/behaviors/meio_upload.php, line 870]
Notice (8): Undefined index:  tmp_name [APP/plugins/meio_upload/models/behaviors/meio_upload.php, line 715]
Notice (8): Undefined index:  type [APP/plugins/meio_upload/models/behaviors/meio_upload.php, line 750]
Notice (8): Undefined index:  size [APP/plugins/meio_upload/models/behaviors/meio_upload.php, line 751]

**Comment by joelpet** [comment] 2009-08-25 11:18
This seems to be somewhat related to the issue I posted about adding a record with no image selected. At least we get the same notices for the same lines of code.

**Comment by josegonzalez** [comment] 2009-12-29 01:11
Duplicate of #6, so I'm closing this as that issue appears to also have disappeared.

**Closed as completed by josegonzalez** 2009-12-29 01:11 UTC
